# This file was generated using _update_libretro_systems.py
from __future__ import annotations

from typing import Final, TypedDict
from typing_extensions import ReadOnly


class CoreDict(TypedDict):
    name: ReadOnly[str]
    systems: ReadOnly[list[str]]
    extensions: ReadOnly[dict[str, list[str]]]


CORES_MAP: Final[dict[str, CoreDict]] = {
    'pocketsnes': {
        'name': 'pocketsnes',
        'systems': ['snes', 'snes-msu1', 'satellaview'],
        'extensions': {
            'snes': ['smc', 'fig', 'sfc', 'gd3', 'gd7', 'dx2', 'bsx', 'swc', 'zip', '7z'],
            'snes-msu1': ['smc', 'sfc', 'squashfs'],
            'satellaview': ['bs', 'smc', 'sfc', 'zip', '7z', 'squashfs'],
        },
    },
    'snes9x_next': {
        'name': 'snes9x_next',
        'systems': ['snes'],
        'extensions': {'snes': ['smc', 'fig', 'sfc', 'gd3', 'gd7', 'dx2', 'bsx', 'swc', 'zip', '7z']},
    },
    'snes9x': {
        'name': 'snes9x',
        'systems': ['snes', 'snes-msu1', 'satellaview', 'sufami'],
        'extensions': {
            'snes': ['smc', 'fig', 'sfc', 'gd3', 'gd7', 'dx2', 'bsx', 'swc', 'zip', '7z'],
            'snes-msu1': ['smc', 'sfc', 'squashfs'],
            'satellaview': ['bs', 'smc', 'sfc', 'zip', '7z', 'squashfs'],
            'sufami': ['st', 'fig', 'bs', 'smc', 'sfc', 'zip', '7z'],
        },
    },
    'bsnes': {
        'name': 'bsnes',
        'systems': ['snes', 'snes-msu1', 'sgb-msu1'],
        'extensions': {
            'snes': ['smc', 'fig', 'sfc', 'gd3', 'gd7', 'dx2', 'bsx', 'swc', 'zip', '7z'],
            'snes-msu1': ['smc', 'sfc', 'squashfs'],
            'sgb-msu1': ['gb', 'gbc', 'zip', '7z', 'squashfs'],
        },
    },
    'bsnes_hd': {
        'name': 'bsnes_hd',
        'systems': ['snes', 'snes-msu1', 'sgb-msu1'],
        'extensions': {
            'snes': ['smc', 'fig', 'sfc', 'gd3', 'gd7', 'dx2', 'bsx', 'swc', 'zip', '7z'],
            'snes-msu1': ['smc', 'sfc', 'squashfs'],
            'sgb-msu1': ['gb', 'gbc', 'zip', '7z', 'squashfs'],
        },
    },
    'mesen-s': {
        'name': 'mesen-s',
        'systems': ['snes', 'gbc', 'gb', 'sgb', 'satellaview'],
        'extensions': {
            'snes': ['smc', 'fig', 'sfc', 'gd3', 'gd7', 'dx2', 'bsx', 'swc', 'zip', '7z'],
            'gbc': ['gbc', 'zip', '7z'],
            'gb': ['gb', 'zip', '7z'],
            'sgb': ['gb', 'gbc', 'zip', '7z'],
            'satellaview': ['bs', 'smc', 'sfc', 'zip', '7z', 'squashfs'],
        },
    },
    'vice_x64': {
        'name': 'vice_x64',
        'systems': ['c64'],
        'extensions': {'c64': ['d64', 'd71', 'd81', 'crt', 'prg', 'tap', 't64', 'm3u', 'zip', '7z', 'nib', 'g64']},
    },
    'vice_x64sc': {
        'name': 'vice_x64sc',
        'systems': ['c64'],
        'extensions': {'c64': ['d64', 'd71', 'd81', 'crt', 'prg', 'tap', 't64', 'm3u', 'zip', '7z', 'nib', 'g64']},
    },
    'vice_xscpu64': {
        'name': 'vice_xscpu64',
        'systems': ['c64'],
        'extensions': {'c64': ['d64', 'd71', 'd81', 'crt', 'prg', 'tap', 't64', 'm3u', 'zip', '7z', 'nib', 'g64']},
    },
    'vice_xplus4': {
        'name': 'vice_xplus4',
        'systems': ['cplus4'],
        'extensions': {'cplus4': ['d64', 'prg', 'tap', 'm3u', 'zip', '7z']},
    },
    'vice_x128': {
        'name': 'vice_x128',
        'systems': ['c128'],
        'extensions': {'c128': ['d64', 'd81', 'prg', 'lnx', 'm3u', 'zip', '7z']},
    },
    'vice_xvic': {
        'name': 'vice_xvic',
        'systems': ['c20'],
        'extensions': {
            'c20': ['20', '40', '60', 'rom', 'a0', 'b0', 'crt', 'd64', 'd81', 'prg', 'tap', 't64', 'm3u', 'zip', '7z']
        },
    },
    'vice_xpet': {
        'name': 'vice_xpet',
        'systems': ['pet'],
        'extensions': {'pet': ['a0', 'b0', 'crt', 'd64', 'd81', 'prg', 'tap', 't64', 'm3u', 'zip', '7z']},
    },
    'puae': {
        'name': 'puae',
        'systems': ['amiga500', 'amiga1200', 'amigacd32', 'amigacdtv'],
        'extensions': {
            'amiga500': ['adf', 'uae', 'ipf', 'dms', 'dmz', 'adz', 'lha', 'hdf', 'exe', 'm3u', 'zip', 'raw', 'scp'],
            'amiga1200': ['adf', 'uae', 'ipf', 'dms', 'dmz', 'adz', 'lha', 'hdf', 'exe', 'm3u', 'zip', 'raw', 'scp'],
            'amigacd32': ['bin', 'cue', 'iso', 'chd'],
            'amigacdtv': ['bin', 'cue', 'iso', 'chd', 'm3u'],
        },
    },
    'puae2021': {
        'name': 'puae2021',
        'systems': ['amiga500', 'amiga1200', 'amigacd32', 'amigacdtv'],
        'extensions': {
            'amiga500': ['adf', 'uae', 'ipf', 'dms', 'dmz', 'adz', 'lha', 'hdf', 'exe', 'm3u', 'zip', 'raw', 'scp'],
            'amiga1200': ['adf', 'uae', 'ipf', 'dms', 'dmz', 'adz', 'lha', 'hdf', 'exe', 'm3u', 'zip', 'raw', 'scp'],
            'amigacd32': ['bin', 'cue', 'iso', 'chd'],
            'amigacdtv': ['bin', 'cue', 'iso', 'chd', 'm3u'],
        },
    },
    'uae4arm': {
        'name': 'uae4arm',
        'systems': ['amiga500', 'amiga1200', 'amigacd32', 'amigacdtv'],
        'extensions': {
            'amiga500': ['adf', 'uae', 'ipf', 'dms', 'dmz', 'adz', 'lha', 'hdf', 'exe', 'm3u', 'zip', 'raw', 'scp'],
            'amiga1200': ['adf', 'uae', 'ipf', 'dms', 'dmz', 'adz', 'lha', 'hdf', 'exe', 'm3u', 'zip', 'raw', 'scp'],
            'amigacd32': ['bin', 'cue', 'iso', 'chd'],
            'amigacdtv': ['bin', 'cue', 'iso', 'chd', 'm3u'],
        },
    },
    'fceumm': {
        'name': 'fceumm',
        'systems': ['nes', 'fds'],
        'extensions': {'nes': ['nes', 'unif', 'unf', 'zip', '7z'], 'fds': ['fds', 'zip', '7z']},
    },
    'nestopia': {
        'name': 'nestopia',
        'systems': ['nes', 'fds'],
        'extensions': {'nes': ['nes', 'unif', 'unf', 'zip', '7z'], 'fds': ['fds', 'zip', '7z']},
    },
    'mesen': {
        'name': 'mesen',
        'systems': ['nes', 'fds'],
        'extensions': {'nes': ['nes', 'unif', 'unf', 'zip', '7z'], 'fds': ['fds', 'zip', '7z']},
    },
    'mupen64plus-next': {
        'name': 'mupen64plus-next',
        'systems': ['n64', 'n64dd'],
        'extensions': {'n64': ['z64', 'n64', 'v64', 'zip', '7z'], 'n64dd': ['z64', 'n64', 'ndd', 'zip', '7z']},
    },
    'parallel_n64': {
        'name': 'parallel_n64',
        'systems': ['n64', 'n64dd'],
        'extensions': {'n64': ['z64', 'n64', 'v64', 'zip', '7z'], 'n64dd': ['z64', 'n64', 'ndd', 'zip', '7z']},
    },
    'mgba': {
        'name': 'mgba',
        'systems': ['gba', 'gbc', 'gb', 'sgb'],
        'extensions': {
            'gba': ['gba', 'zip', '7z'],
            'gbc': ['gbc', 'zip', '7z'],
            'gb': ['gb', 'zip', '7z'],
            'sgb': ['gb', 'gbc', 'zip', '7z'],
        },
    },
    'vba-m': {
        'name': 'vba-m',
        'systems': ['gba', 'gbc', 'gb'],
        'extensions': {'gba': ['gba', 'zip', '7z'], 'gbc': ['gbc', 'zip', '7z'], 'gb': ['gb', 'zip', '7z']},
    },
    'gpsp': {'name': 'gpsp', 'systems': ['gba'], 'extensions': {'gba': ['gba', 'zip', '7z']}},
    'gambatte': {
        'name': 'gambatte',
        'systems': ['gbc', 'gb'],
        'extensions': {'gbc': ['gbc', 'zip', '7z'], 'gb': ['gb', 'zip', '7z']},
    },
    'tgbdual': {
        'name': 'tgbdual',
        'systems': ['gbc2players', 'gb2players'],
        'extensions': {
            'gbc2players': ['gbc', 'gb2', 'gbc2', 'zip', '7z'],
            'gb2players': ['gb', 'gb2', 'gbc2', 'zip', '7z'],
        },
    },
    'desmume': {'name': 'desmume', 'systems': ['nds'], 'extensions': {'nds': ['nds', 'bin', 'zip', '7z']}},
    'melonds': {'name': 'melonds', 'systems': ['nds'], 'extensions': {'nds': ['nds', 'bin', 'zip', '7z']}},
    'melondsds': {'name': 'melondsds', 'systems': ['nds'], 'extensions': {'nds': ['nds', 'bin', 'zip', '7z']}},
    'vb': {'name': 'vb', 'systems': ['virtualboy'], 'extensions': {'virtualboy': ['vb', 'zip', '7z']}},
    'mame': {
        'name': 'mame',
        'systems': [
            'lcdgames',
            'gameandwatch',
            'mame',
            'neogeo',
            'xegs',
            'apple2',
            'fmtowns',
            'model2',
            'apple2gs',
            'advision',
            'plugnplay',
            'megaduck',
            'pv1000',
            'gamate',
            'crvision',
            'laser310',
            'socrates',
            'vsmile',
            'supracan',
            'gamecom',
            'gamepock',
            'fm7',
            'archimedes',
            'atom',
            'electron',
            'apfm1000',
            'bbc',
            'camplynx',
            'adam',
            'arcadia',
            'gmaster',
            'astrocde',
            'ti99',
            'tutor',
            'coco',
            'vc4000',
            'vgmplay',
            'macintosh',
            'pdp1',
            'gp32',
            'vis',
            'namco22',
        ],
        'extensions': {
            'lcdgames': ['mgw', 'zip', '7z'],
            'gameandwatch': ['mgw', 'zip', '7z'],
            'mame': ['zip', '7z'],
            'neogeo': ['7z', 'zip'],
            'xegs': ['atr', 'dsk', 'xfd', 'bin', 'rom', 'car', 'zip', '7z'],
            'apple2': [
                'nib',
                'do',
                'po',
                'dsk',
                'mfi',
                'dfi',
                'rti',
                'edd',
                'woz',
                'wav',
                'zip',
                '7z',
                'chd',
                'hdv',
                '2mg',
            ],
            'fmtowns': [
                'bin',
                'cue',
                'd88',
                'd77',
                'iso',
                'chd',
                'toc',
                'nrg',
                'gdi',
                'cdr',
                'mfi',
                'dfi',
                'hfe',
                'mfm',
                'td0',
                'imd',
                '1dd',
                'cqm',
                'cqi',
                'dsk',
                'zip',
                '7z',
            ],
            'model2': ['zip'],
            'apple2gs': [
                '2mg',
                'do',
                'nib',
                'po',
                'dsk',
                'mfi',
                'dfi',
                'rti',
                'edd',
                'woz',
                'hfe',
                'mfm',
                'td0',
                'imd',
                'd77',
                'd88',
                '1dd',
                'cqm',
                'cqui',
                'ima',
                'img',
                'ufi',
                '360',
                'ipf',
                'dc42',
                'zip',
                '7z',
            ],
            'advision': ['bin', 'zip', '7z'],
            'plugnplay': ['zip', '7z'],
            'megaduck': ['bin', 'zip', '7z'],
            'pv1000': ['bin', 'zip', '7z'],
            'gamate': ['bin', 'zip', '7z'],
            'crvision': ['bin', 'rom', 'zip', '7z'],
            'laser310': ['vz', 'wav', 'cas', 'zip', '7z'],
            'socrates': ['bin', 'zip', '7z'],
            'vsmile': ['u1', 'u3', 'bin', 'zip', '7z'],
            'supracan': ['bin', 'zip', '7z'],
            'gamecom': ['bin', 'tgc', 'zip', '7z'],
            'gamepock': ['bin', 'zip', '7z'],
            'fm7': [
                'wav',
                't77',
                'mfi',
                'dfi',
                'hfe',
                'mfm',
                'td0',
                'imd',
                'd77',
                'd88',
                '1dd',
                'cqm',
                'cqi',
                'dsk',
                'zip',
                '7z',
            ],
            'archimedes': [
                'mfi',
                'dfi',
                'hfe',
                'mfm',
                'td0',
                'imd',
                'd77',
                'd88',
                '1dd',
                'cqm',
                'cqi',
                'dsk',
                'ima',
                'img',
                'ufi',
                '360',
                'ipf',
                'adf',
                'apd',
                'jfd',
                'ads',
                'adm',
                'adl',
                'ssd',
                'bbc',
                'dsd',
                'st',
                'msa',
                'chd',
                'zip',
                '7z',
            ],
            'atom': [
                'wav',
                'tap',
                'csw',
                'uef',
                'mfi',
                'dfi',
                'hfe',
                'mfm',
                'td0',
                'imd',
                'd77',
                'd88',
                '1dd',
                'cqm',
                'cqi',
                'dsk',
                '40t',
                'atm',
                'bin',
                'rom',
                'zip',
                '7z',
            ],
            'electron': [
                'wav',
                'csw',
                'uef',
                'mfi',
                'dfi',
                'hfe',
                'mfm',
                'td0',
                'imd',
                'd77',
                'd88',
                '1dd',
                'cqm',
                'cqi',
                'dsk',
                'ssd',
                'bbc',
                'img',
                'dsd',
                'adf',
                'ads',
                'adm',
                'adl',
                'rom',
                'bin',
                'zip',
                '7z',
            ],
            'apfm1000': ['bin', 'zip', '7z'],
            'bbc': [
                'mfi',
                'dfi',
                'hfe',
                'mfm',
                'td0',
                'imd',
                'd77',
                'd88',
                '1dd',
                'cqm',
                'cqi',
                'dsk',
                'ima',
                'img',
                'ufi',
                '360',
                'ipf',
                'ssd',
                'bbc',
                'dsd',
                'adf',
                'ads',
                'adm',
                'adl',
                'fsd',
                'wav',
                'tap',
                'bin',
                'zip',
                '7z',
            ],
            'camplynx': ['wav', 'tap', 'ldf', 'zip', '7z'],
            'adam': [
                'wav',
                'ddp',
                'mfi',
                'dfi',
                'hfe',
                'mfm',
                'td0',
                'imd',
                'd77',
                'd88',
                '1dd',
                'cqm',
                'cqi',
                'dsk',
                'rom',
                'col',
                'bin',
                'zip',
                '7z',
            ],
            'arcadia': ['bin', 'zip', '7z'],
            'gmaster': ['bin', 'zip', '7z'],
            'astrocde': ['bin', 'zip', '7z'],
            'ti99': ['rpk', 'wav', 'zip', '7z'],
            'tutor': ['bin', 'wav', 'zip', '7z'],
            'coco': ['wav', 'cas', 'dsk', 'ccc', 'rom', 'zip', '7z'],
            'vc4000': ['bin', 'rom', 'pgm', 'tvc', 'zip', '7z'],
            'vgmplay': ['vgm', 'vgz', 'zip', '7z'],
            'macintosh': [
                'dsk',
                'zip',
                '7z',
                'mfi',
                'dfi',
                'hfe',
                'mfm',
                'td0',
                'imd',
                'd77',
                'd88',
                '1dd',
                'cqm',
                'cqi',
                'dsk',
                'ima',
                'img',
                'ufi',
                'ipf',
                'dc42',
                'woz',
                '2mg',
                '360',
                'chd',
                'cue',
                'toc',
                'nrg',
                'gdi',
                'iso',
                'cdr',
                'hd',
                'hdv',
                '2mg',
                'hdi',
            ],
            'pdp1': ['zip', '7z', 'tap', 'rim', 'drm'],
            'gp32': ['smc', 'zip', '7z'],
            'vis': ['chd', 'cue', 'toc', 'nrg', 'gdi', 'iso', 'cdr'],
            'namco22': ['zip', '7z'],
        },
    },
    'gw': {'name': 'gw', 'systems': ['gameandwatch'], 'extensions': {'gameandwatch': ['mgw', 'zip', '7z']}},
    'flycast': {
        'name': 'flycast',
        'systems': ['dreamcast', 'naomi', 'atomiswave', 'systemsp', 'naomi2'],
        'extensions': {
            'dreamcast': ['cdi', 'cue', 'gdi', 'chd', 'm3u'],
            'naomi': ['lst', 'bin', 'dat', 'zip', '7z'],
            'atomiswave': ['lst', 'bin', 'dat', 'zip', '7z'],
            'systemsp': ['lst', 'bin', 'dat', 'zip', '7z'],
            'naomi2': ['zip', '7z'],
        },
    },
    'flycastvl': {
        'name': 'flycastvl',
        'systems': ['dreamcast', 'naomi', 'atomiswave'],
        'extensions': {
            'dreamcast': ['cdi', 'cue', 'gdi', 'chd', 'm3u'],
            'naomi': ['lst', 'bin', 'dat', 'zip', '7z'],
            'atomiswave': ['lst', 'bin', 'dat', 'zip', '7z'],
        },
    },
    'genesisplusgx': {
        'name': 'genesisplusgx',
        'systems': ['megadrive', 'megacd', 'msu-md', 'mastersystem', 'pico', 'gamegear', 'sg1000'],
        'extensions': {
            'megadrive': ['bin', 'gen', 'md', 'sg', 'smd', 'zip', '7z'],
            'megacd': ['cue', 'iso', 'chd', 'm3u'],
            'msu-md': ['md', 'zip', '7z', 'squashfs'],
            'mastersystem': ['bin', 'sms', 'zip', '7z'],
            'pico': ['bin', 'md', 'zip', '7z'],
            'gamegear': ['bin', 'gg', 'zip', '7z'],
            'sg1000': ['bin', 'sg', 'zip', '7z'],
        },
    },
    'genesisplusgx-expanded': {
        'name': 'genesisplusgx-expanded',
        'systems': ['megadrive'],
        'extensions': {'megadrive': ['bin', 'gen', 'md', 'sg', 'smd', 'zip', '7z']},
    },
    'genesisplusgx-wide': {
        'name': 'genesisplusgx-wide',
        'systems': ['megadrive', 'msu-md', 'pico'],
        'extensions': {
            'megadrive': ['bin', 'gen', 'md', 'sg', 'smd', 'zip', '7z'],
            'msu-md': ['md', 'zip', '7z', 'squashfs'],
            'pico': ['bin', 'md', 'zip', '7z'],
        },
    },
    'picodrive': {
        'name': 'picodrive',
        'systems': ['megadrive', 'megacd', 'sega32x', 'mastersystem', 'pico', 'gamegear'],
        'extensions': {
            'megadrive': ['bin', 'gen', 'md', 'sg', 'smd', 'zip', '7z'],
            'megacd': ['cue', 'iso', 'chd', 'm3u'],
            'sega32x': ['32x', 'chd', 'smd', 'bin', 'md', 'zip', '7z'],
            'mastersystem': ['bin', 'sms', 'zip', '7z'],
            'pico': ['bin', 'md', 'zip', '7z'],
            'gamegear': ['bin', 'gg', 'zip', '7z'],
        },
    },
    'blastem': {
        'name': 'blastem',
        'systems': ['megadrive'],
        'extensions': {'megadrive': ['bin', 'gen', 'md', 'sg', 'smd', 'zip', '7z']},
    },
    'smsplus': {
        'name': 'smsplus',
        'systems': ['mastersystem', 'gamegear'],
        'extensions': {'mastersystem': ['bin', 'sms', 'zip', '7z'], 'gamegear': ['bin', 'gg', 'zip', '7z']},
    },
    'gearsystem': {
        'name': 'gearsystem',
        'systems': ['mastersystem', 'gamegear', 'sg1000', 'multivision'],
        'extensions': {
            'mastersystem': ['bin', 'sms', 'zip', '7z'],
            'gamegear': ['bin', 'gg', 'zip', '7z'],
            'sg1000': ['bin', 'sg', 'zip', '7z'],
            'multivision': ['bin', 'sg', 'zip', '7z'],
        },
    },
    'ppsspp': {'name': 'ppsspp', 'systems': ['psp'], 'extensions': {'psp': ['iso', 'cso', 'pbp', 'chd']}},
    'pcsx_rearmed': {
        'name': 'pcsx_rearmed',
        'systems': ['psx'],
        'extensions': {'psx': ['cue', 'img', 'mdf', 'pbp', 'toc', 'cbn', 'm3u', 'ccd', 'chd', 'iso']},
    },
    'swanstation': {
        'name': 'swanstation',
        'systems': ['psx'],
        'extensions': {'psx': ['cue', 'img', 'mdf', 'pbp', 'toc', 'cbn', 'm3u', 'ccd', 'chd', 'iso']},
    },
    'mednafen_psx': {
        'name': 'mednafen_psx',
        'systems': ['psx'],
        'extensions': {'psx': ['cue', 'img', 'mdf', 'pbp', 'toc', 'cbn', 'm3u', 'ccd', 'chd', 'iso']},
    },
    'pce': {
        'name': 'pce',
        'systems': ['pcengine', 'pcenginecd'],
        'extensions': {
            'pcengine': ['pce', 'bin', 'zip', '7z'],
            'pcenginecd': ['pce', 'cue', 'ccd', 'iso', 'img', 'chd'],
        },
    },
    'pce_fast': {
        'name': 'pce_fast',
        'systems': ['pcengine', 'pcenginecd'],
        'extensions': {
            'pcengine': ['pce', 'bin', 'zip', '7z'],
            'pcenginecd': ['pce', 'cue', 'ccd', 'iso', 'img', 'chd'],
        },
    },
    'mednafen_supergrafx': {
        'name': 'mednafen_supergrafx',
        'systems': ['supergrafx'],
        'extensions': {'supergrafx': ['pce', 'sgx', 'cue', 'ccd', 'chd', 'zip', '7z']},
    },
    'pcfx': {
        'name': 'pcfx',
        'systems': ['pcfx'],
        'extensions': {'pcfx': ['cue', 'ccd', 'toc', 'chd', 'zip', '7z', 'm3u']},
    },
    'scummvm': {'name': 'scummvm', 'systems': ['scummvm'], 'extensions': {'scummvm': ['scummvm', 'squashfs']}},
    'dosbox_pure': {
        'name': 'dosbox_pure',
        'systems': ['dos'],
        'extensions': {'dos': ['pc', 'dos', 'zip', 'squashfs', 'dosz', 'm3u', 'iso', 'cue']},
    },
    'fbalpha': {
        'name': 'fbalpha',
        'systems': ['fbneo', 'neogeo'],
        'extensions': {'fbneo': ['zip', '7z'], 'neogeo': ['7z', 'zip']},
    },
    'fbneo': {
        'name': 'fbneo',
        'systems': ['fbneo', 'neogeo'],
        'extensions': {'fbneo': ['zip', '7z'], 'neogeo': ['7z', 'zip']},
    },
    'imame4all': {
        'name': 'imame4all',
        'systems': ['mame', 'neogeo'],
        'extensions': {'mame': ['zip', '7z'], 'neogeo': ['7z', 'zip']},
    },
    'mame078plus': {
        'name': 'mame078plus',
        'systems': ['mame', 'neogeo'],
        'extensions': {'mame': ['zip', '7z'], 'neogeo': ['7z', 'zip']},
    },
    'neocd': {'name': 'neocd', 'systems': ['neogeocd'], 'extensions': {'neogeocd': ['cue', 'iso', 'chd']}},
    'bluemsx': {
        'name': 'bluemsx',
        'systems': ['colecovision', 'msx1', 'msx2', 'msx2+', 'msxturbor', 'spectravideo'],
        'extensions': {
            'colecovision': ['bin', 'col', 'rom', 'zip', '7z'],
            'msx1': ['dsk', 'mx1', 'rom', 'zip', '7z', 'cas', 'm3u'],
            'msx2': ['dsk', 'mx2', 'rom', 'zip', '7z', 'cas', 'm3u', 'ogv'],
            'msx2+': ['dsk', 'mx2', 'rom', 'zip', '7z', 'cas', 'm3u'],
            'msxturbor': ['dsk', 'mx2', 'rom', 'zip', '7z', 'm3u'],
            'spectravideo': ['zip', '7z', 'cas'],
        },
    },
    'atari800': {
        'name': 'atari800',
        'systems': ['atari800', 'atari5200'],
        'extensions': {
            'atari800': ['rom', 'xfd', 'atr', 'atx', 'cdm', 'cas', 'car', 'bin', 'a52', 'xex', 'zip', '7z', 'm3u'],
            'atari5200': ['rom', 'xfd', 'atr', 'atx', 'cdm', 'cas', 'car', 'bin', 'a52', 'xex', 'zip', '7z'],
        },
    },
    'stella': {'name': 'stella', 'systems': ['atari2600'], 'extensions': {'atari2600': ['a26', 'bin', 'zip', '7z']}},
    'stella2014': {
        'name': 'stella2014',
        'systems': ['atari2600'],
        'extensions': {'atari2600': ['a26', 'bin', 'zip', '7z']},
    },
    'a5200': {
        'name': 'a5200',
        'systems': ['atari5200'],
        'extensions': {
            'atari5200': ['rom', 'xfd', 'atr', 'atx', 'cdm', 'cas', 'car', 'bin', 'a52', 'xex', 'zip', '7z']
        },
    },
    'prosystem': {
        'name': 'prosystem',
        'systems': ['atari7800'],
        'extensions': {'atari7800': ['a78', 'bin', 'zip', '7z']},
    },
    'mednafen_lynx': {
        'name': 'mednafen_lynx',
        'systems': ['lynx'],
        'extensions': {'lynx': ['bll', 'lnx', 'lyx', 'o', 'zip', '7z']},
    },
    'handy': {'name': 'handy', 'systems': ['lynx'], 'extensions': {'lynx': ['bll', 'lnx', 'lyx', 'o', 'zip', '7z']}},
    'holani': {'name': 'holani', 'systems': ['lynx'], 'extensions': {'lynx': ['bll', 'lnx', 'lyx', 'o', 'zip', '7z']}},
    'mednafen_ngp': {
        'name': 'mednafen_ngp',
        'systems': ['ngp', 'ngpc'],
        'extensions': {'ngp': ['ngp', 'zip', '7z'], 'ngpc': ['ngc', 'zip', '7z']},
    },
    'mednafen_wswan': {
        'name': 'mednafen_wswan',
        'systems': ['wswan', 'wswanc'],
        'extensions': {'wswan': ['ws', 'zip', '7z'], 'wswanc': ['wsc', 'zip', '7z']},
    },
    'prboom': {'name': 'prboom', 'systems': ['prboom'], 'extensions': {'prboom': ['wad', 'iwad', 'pwad']}},
    'tyrquake': {'name': 'tyrquake', 'systems': ['quake'], 'extensions': {'quake': ['quake']}},
    'mrboom': {'name': 'mrboom', 'systems': ['mrboom'], 'extensions': {'mrboom': ['libretro']}},
    'tic80': {'name': 'tic80', 'systems': ['tic80'], 'extensions': {'tic80': ['tic']}},
    'fake08': {'name': 'fake08', 'systems': ['pico8'], 'extensions': {'pico8': ['p8', 'png', 'm3u']}},
    'lowresnx': {'name': 'lowresnx', 'systems': ['lowresnx'], 'extensions': {'lowresnx': ['nx', 'zip', '7z']}},
    'wasm4': {'name': 'wasm4', 'systems': ['wasm4'], 'extensions': {'wasm4': ['wasm']}},
    'vircon32': {'name': 'vircon32', 'systems': ['vircon32'], 'extensions': {'vircon32': ['v32', 'zip']}},
    'freechaf': {'name': 'freechaf', 'systems': ['channelf'], 'extensions': {'channelf': ['zip', 'rom', 'bin', 'chf']}},
    'vecx': {'name': 'vecx', 'systems': ['vectrex'], 'extensions': {'vectrex': ['bin', 'gam', 'vec', 'zip', '7z']}},
    'lutro': {'name': 'lutro', 'systems': ['lutro'], 'extensions': {'lutro': ['lutro', 'zip', '7z']}},
    'nxengine': {'name': 'nxengine', 'systems': ['cavestory'], 'extensions': {'cavestory': ['exe']}},
    'hatarib': {
        'name': 'hatarib',
        'systems': ['atarist'],
        'extensions': {'atarist': ['st', 'msa', 'stx', 'dim', 'ipf', 'm3u', 'zip', '7z', 'hd', 'gemdos']},
    },
    'hatari': {
        'name': 'hatari',
        'systems': ['atarist'],
        'extensions': {'atarist': ['st', 'msa', 'stx', 'dim', 'ipf', 'm3u', 'zip', '7z']},
    },
    'cap32': {
        'name': 'cap32',
        'systems': ['amstradcpc', 'gx4000'],
        'extensions': {
            'amstradcpc': ['dsk', 'sna', 'tap', 'cdt', 'voc', 'm3u', 'zip', '7z'],
            'gx4000': ['dsk', 'm3u', 'cpr', 'zip', '7z'],
        },
    },
    'fmsx': {
        'name': 'fmsx',
        'systems': ['msx1', 'msx2', 'msx2+'],
        'extensions': {
            'msx1': ['dsk', 'mx1', 'rom', 'zip', '7z', 'cas', 'm3u'],
            'msx2': ['dsk', 'mx2', 'rom', 'zip', '7z', 'cas', 'm3u', 'ogv'],
            'msx2+': ['dsk', 'mx2', 'rom', 'zip', '7z', 'cas', 'm3u'],
        },
    },
    'o2em': {
        'name': 'o2em',
        'systems': ['o2em', 'videopacplus'],
        'extensions': {'o2em': ['bin', 'zip', '7z'], 'videopacplus': ['bin', 'zip', '7z']},
    },
    '81': {'name': '81', 'systems': ['zx81'], 'extensions': {'zx81': ['tzx', 'p', 'zip', '7z']}},
    'fuse': {
        'name': 'fuse',
        'systems': ['zxspectrum'],
        'extensions': {'zxspectrum': ['tzx', 'tap', 'z80', 'rzx', 'scl', 'trd', 'dsk', 'zip', '7z']},
    },
    'applewin': {
        'name': 'applewin',
        'systems': ['apple2'],
        'extensions': {
            'apple2': [
                'nib',
                'do',
                'po',
                'dsk',
                'mfi',
                'dfi',
                'rti',
                'edd',
                'woz',
                'wav',
                'zip',
                '7z',
                'chd',
                'hdv',
                '2mg',
            ]
        },
    },
    'beetle-saturn': {
        'name': 'beetle-saturn',
        'systems': ['saturn'],
        'extensions': {'saturn': ['cue', 'ccd', 'm3u', 'chd', 'iso', 'mds']},
    },
    'kronos': {
        'name': 'kronos',
        'systems': ['saturn'],
        'extensions': {'saturn': ['cue', 'ccd', 'm3u', 'chd', 'iso', 'zip', 'mds']},
    },
    'yabasanshiro': {
        'name': 'yabasanshiro',
        'systems': ['saturn'],
        'extensions': {'saturn': ['cue', 'ccd', 'chd', 'iso', 'zip', 'mds']},
    },
    'virtualjaguar': {
        'name': 'virtualjaguar',
        'systems': ['jaguar', 'jaguarcd'],
        'extensions': {'jaguar': ['j64', 'jag', 'cof', 'abs', 'rom', 'zip'], 'jaguarcd': ['cue', 'cdi', 'bigpimg']},
    },
    'dolphin': {
        'name': 'dolphin',
        'systems': ['gamecube', 'wii'],
        'extensions': {
            'gamecube': ['gcm', 'iso', 'gcz', 'ciso', 'wbfs', 'rvz', 'elf', 'dol', 'm3u', 'json'],
            'wii': ['gcm', 'iso', 'gcz', 'ciso', 'wbfs', 'wad', 'rvz', 'elf', 'dol', 'm3u', 'json'],
        },
    },
    'pcsx2': {
        'name': 'pcsx2',
        'systems': ['ps2'],
        'extensions': {'ps2': ['iso', 'mdf', 'nrg', 'bin', 'img', 'dump', 'gz', 'cso', 'chd']},
    },
    'play': {
        'name': 'play',
        'systems': ['ps2'],
        'extensions': {'ps2': ['iso', 'mdf', 'nrg', 'bin', 'img', 'dump', 'gz', 'cso', 'chd']},
    },
    'opera': {'name': 'opera', 'systems': ['3do'], 'extensions': {'3do': ['iso', 'chd', 'cue']}},
    'freeintv': {
        'name': 'freeintv',
        'systems': ['intellivision'],
        'extensions': {'intellivision': ['int', 'bin', 'rom', 'zip', '7z']},
    },
    'px68k': {
        'name': 'px68k',
        'systems': ['x68000'],
        'extensions': {
            'x68000': ['dim', 'img', 'd88', '88d', 'hdm', 'dup', '2hd', 'xdf', 'hdf', 'cmd', 'm3u', 'zip', '7z']
        },
    },
    'x1': {
        'name': 'x1',
        'systems': ['x1'],
        'extensions': {'x1': ['dx1', 'zip', '2d', '2hd', 'tfd', 'd88', '88d', 'hdm', 'xdf', 'dup', 'cmd', '7z']},
    },
    'pokemini': {'name': 'pokemini', 'systems': ['pokemini'], 'extensions': {'pokemini': ['min', 'zip', '7z']}},
    'dice': {'name': 'dice', 'systems': ['dice'], 'extensions': {'dice': ['zip', 'dmy']}},
    'theodore': {
        'name': 'theodore',
        'systems': ['thomson'],
        'extensions': {'thomson': ['fd', 'sap', 'k7', 'm7', 'm5', 'rom', 'zip']},
    },
    'quasi88': {'name': 'quasi88', 'systems': ['pc88'], 'extensions': {'pc88': ['cmt', 'd88', 'u88', 'm3u']}},
    'np2kai': {
        'name': 'np2kai',
        'systems': ['pc98'],
        'extensions': {
            'pc98': [
                'd98',
                'zip',
                '98d',
                'fdi',
                'fdd',
                '2hd',
                'tfd',
                'd88',
                '88d',
                'hdm',
                'xdf',
                'dup',
                'cmd',
                'hdi',
                'thd',
                'nhd',
                'hdd',
                'hdn',
                'm3u',
            ]
        },
    },
    'easyrpg': {'name': 'easyrpg', 'systems': ['easyrpg'], 'extensions': {'easyrpg': ['easyrpg', 'squashfs', 'zip']}},
    'potator': {'name': 'potator', 'systems': ['supervision'], 'extensions': {'supervision': ['sv', 'zip', '7z']}},
    'gong': {'name': 'gong', 'systems': ['gong'], 'extensions': {'gong': ['game']}},
    'emuscv': {'name': 'emuscv', 'systems': ['scv'], 'extensions': {'scv': ['bin', 'zip', '0']}},
    'uzem': {'name': 'uzem', 'systems': ['uzebox'], 'extensions': {'uzebox': ['uze']}},
    'same_cdi': {'name': 'same_cdi', 'systems': ['cdi'], 'extensions': {'cdi': ['chd', 'iso']}},
    'sameduck': {'name': 'sameduck', 'systems': ['megaduck'], 'extensions': {'megaduck': ['bin', 'zip', '7z']}},
    'superbroswar': {'name': 'superbroswar', 'systems': ['superbroswar'], 'extensions': {'superbroswar': ['game']}},
    'vitaquake2': {'name': 'vitaquake2', 'systems': ['quake2'], 'extensions': {'quake2': ['quake2', 'zip', '7zip']}},
    'squirreljme': {'name': 'squirreljme', 'systems': ['j2me'], 'extensions': {'j2me': ['jar']}},
    'freej2me': {'name': 'freej2me', 'systems': ['j2me'], 'extensions': {'j2me': ['jar']}},
    'zc210': {'name': 'zc210', 'systems': ['zc210'], 'extensions': {'zc210': ['qst']}},
    'vemulator': {'name': 'vemulator', 'systems': ['vemulator'], 'extensions': {'vemulator': ['vms', 'dci', 'bin']}},
    'xrick': {'name': 'xrick', 'systems': ['xrick'], 'extensions': {'xrick': ['zip']}},
    'minivmac': {'name': 'minivmac', 'systems': ['macintosh'], 'extensions': {'macintosh': ['zip']}},
    'arduous': {'name': 'arduous', 'systems': ['arduboy'], 'extensions': {'arduboy': ['hex', 'zip', '7z']}},
    'boom3': {'name': 'boom3', 'systems': ['doom3'], 'extensions': {'doom3': ['d3']}},
    'reminiscence': {'name': 'reminiscence', 'systems': ['reminiscence'], 'extensions': {'reminiscence': ['rem']}},
    'bennugd': {'name': 'bennugd', 'systems': ['bennugd'], 'extensions': {'bennugd': ['dcb', 'dat']}},
}
